# job name and event such as push pull
name: My First Workflow
on:
  push:
    branches: [main]
# job name and where to run    
jobs:
  ourbuild:
   runs-on: ubuntu-22.04 #github runner slave
   # add the steps
   steps:
     - name: checkout-repository
       uses: actions/checkout@v4
     - name: Display Message
       run: echo "Hello, GitHub Actions!"

     - name: Show Current Directory
       run: pwd

     - name: List Files
       run: ls -la

     - name: Display Date
       run: date
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and push
       run: |
        docker build -t myusername/myapp:${{ github.sha }} .
         docker push myusername/myapp:${{ github.sha }}
   

