# job name and event such as push pull
name: My First Workflow
on:
  push:
    branches: [main]
# job name and where to run    
jobs:
  ourbuild:
   runs-on: ubuntu-22.04 #github runner slave
   # add the steps
   steps:
     - name: checkout-repository
       uses: actions/checkout@v4
     - name: build docker image and tool
       uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: srinathreddy/my-node-app:${{ github.run_number }}
       
        
   
     - 
   
     - 

